//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XnxGaming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchRequest
    {
        public int Id { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string CompanyId { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string EditUserId { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> SenderTeamId { get; set; }
        public bool IsAccepted { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public Nullable<int> ReceiverTeamId { get; set; }
        public int Status { get; set; }
        public System.DateTime MatchTimings { get; set; }
        public int MatchType { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
